inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - 'lib/**/*'
  Exclude:
    - 'bin/*'
    - 'spec/*'
    - 'spec/**/*'
    - 'script/**/*'
    - 'test/*'
    - 'vendor/**/*'
    - 'examples/**/*'
    - 'profile/**/*'
    - 'tmp/**/*'
    - 'lib/**/*.liquid'
    - 'deprecated/**/*'
    - '*'
  DisplayCopNames: true
  TargetRubyVersion: '2.3'

# My personal style
# -----------------
# See http://zverok.github.io/blog/2016-02-23-control-flow.html
Style/AndOr:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/BlockDelimiters:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: when_needed

Style/SignalException:
  EnforcedStyle: semantic

# Generated code: hard to support some conventions:
# -------------------------------------------------

Style/DefWithParentheses:
  Exclude:
    - 'lib/mediawiktory/wikipedia/**/*'

Style/MethodName:
  Exclude:
    - 'lib/mediawiktory/wikipedia/**/*'

Style/ClassAndModuleChildren:
  Exclude:
    - 'lib/mediawiktory/wikipedia/**/*'

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'lib/mediawiktory/wikipedia/**/*'

Style/EmptyLinesAroundClassBody:
  Exclude:
    - 'lib/mediawiktory/wikipedia/**/*'

Style/EmptyLinesAroundModuleBody:
  Exclude:
    - 'lib/mediawiktory/wikipedia/**/*'

Style/TrailingWhitespace:
  Exclude:
    - 'lib/mediawiktory/wikipedia/**/*'
