cache: bundler
language: ruby
rvm:
  - "2.1"
  - "2.2"
  - "2.3.0"
  - "2.4.0"
  #- jruby-19mode # Due to https://github.com/jruby/jruby/issues/2599
install:
  - bundle install --retry=3 --without development docs
script:
  - bundle exec rspec
