cache: bundler
language: ruby
rvm:
  - "2.1"
  - "2.2"
  - "2.3.0"
  - "2.4.0"
  - jruby-head
before_install:
  - gem install bundler
install:
  - bundle install --retry=3 --without development docs
script:
  - bundle exec rspec
